## Data retrieval for curatedOvarianData: datasets are hosted on Zenodo and
## downloaded on first use into a package-specific BiocFileCache.
##
## NOTE: this file is intentionally duplicated (modulo package name) in
## curatedCRCData. Keep the two copies in sync.

.pkgname <- "curatedOvarianData"

## session flags (e.g., show the data() deprecation note only once)
.pkgenv <- new.env(parent = emptyenv())

## Manifest mapping dataset names to Zenodo file URLs, md5 checksums, and
## sizes. Regenerated by inst/scripts/make-data.R; the manifest is the ONLY
## place download URLs live.
.manifest <- function() {
    fname <- system.file("extdata", "zenodo-manifest.csv",
                         package = .pkgname, mustWork = TRUE)
    utils::read.csv(fname, stringsAsFactors = FALSE)
}

.cache <- function() {
    BiocFileCache::BiocFileCache(tools::R_user_dir(.pkgname, "cache"))
}

## Return the local path to one dataset's .rda, downloading into the cache
## on first use. The md5 checksum is verified after a fresh download only;
## on mismatch the corrupt entry is removed and the download retried once.
.getDataFile <- function(name, retry = TRUE) {
    meta <- .manifest()
    i <- match(name, meta$dataset)
    stopifnot(!is.na(i))
    bfc <- .cache()
    known <- BiocFileCache::bfcquery(bfc, meta$url[i], field = "fpath",
                                     exact = TRUE)
    fresh <- nrow(known) == 0L
    if (fresh)
        message("Downloading ", name, " (",
                round(meta$size_bytes[i] / 2^20, 1), " MB) from Zenodo...")
    path <- unname(BiocFileCache::bfcrpath(bfc, meta$url[i]))
    if (!fresh && !isTRUE(file.size(path) == meta$size_bytes[i])) {
        # cached file was truncated or modified after download: evict and
        # re-download (cheap size check; full md5 runs after each download)
        res <- BiocFileCache::bfcquery(bfc, meta$url[i], field = "fpath",
                                       exact = TRUE)
        if (nrow(res))
            BiocFileCache::bfcremove(bfc, res$rid)
        if (retry) {
            message("Cached copy of ", name,
                    " has the wrong size; re-downloading...")
            return(.getDataFile(name, retry = FALSE))
        }
        stop("Cached file for '", name, "' has the wrong size and could ",
             "not be refreshed.")
    }
    if (fresh) {
        md5 <- unname(tools::md5sum(path))
        if (!identical(md5, meta$md5[i])) {
            res <- BiocFileCache::bfcquery(bfc, meta$url[i], field = "fpath",
                                           exact = TRUE)
            if (nrow(res))
                BiocFileCache::bfcremove(bfc, res$rid)
            if (retry) {
                message("Checksum mismatch; retrying the download once...")
                return(.getDataFile(name, retry = FALSE))
            }
            stop("md5 checksum mismatch for '", name, "' downloaded from ",
                 meta$url[i],
                 "; the corrupt copy was removed from the cache.")
        }
    }
    path
}

.loadOne <- function(name, test = FALSE) {
    path <- if (test) {
        system.file("extdata", "testdata", paste0(name, ".rda"),
                    package = .pkgname, mustWork = TRUE)
    } else {
        .getDataFile(name)
    }
    env <- new.env(parent = emptyenv())
    objname <- load(path, envir = env)
    get(objname[1L], envir = env)
}

## Called by the data/*.R stubs so that legacy data(X) usage keeps working.
## During this package's own R CMD check, resolve to the bundled test
## fixture so checking needs no network access; checks of OTHER packages
## (reverse dependencies) get the real data.
.stubLoad <- function(name) {
    if (identical(Sys.getenv("_R_CHECK_PACKAGE_NAME_"), .pkgname))
        return(.loadOne(name, test = TRUE))
    if (!isTRUE(.pkgenv$stub_noted)) {
        .pkgenv$stub_noted <- TRUE
        message("Note: loading ", .pkgname, " datasets via data() is ",
                "deprecated and will be removed in a future release; use ",
                .pkgname, "(\"", name, "\") instead. Datasets are now ",
                "downloaded on first use and cached locally with ",
                "BiocFileCache. (This note is shown once per session.)")
    }
    .loadOne(name)
}

#' @export
curatedOvarianData <- function(datasets, test = FALSE) {
    meta <- .manifest()
    if (missing(datasets))
        return(meta$dataset)
    stopifnot(is.character(datasets), !anyNA(datasets))
    bad <- setdiff(datasets, meta$dataset)
    if (length(bad))
        stop("Unknown dataset(s): ", paste(bad, collapse = ", "),
             ". Call curatedOvarianData() with no arguments to list ",
             "available datasets.")
    res <- lapply(datasets, .loadOne, test = test)
    names(res) <- datasets
    if (length(res) == 1L) res[[1L]] else res
}
